-- as-tradingcards / custom/cards.lua
-- Generated by Card Creator

Config.Cards = Config.Cards or {}

Config.Cards['card_kane_harbour'] = {
    name = 'Kane Harbour',
    theme = 'football',
    description = 'A striker who never misses.',
    image = '',
    rarity = 'Rare',
    finish = 'holo',
    set = 'season_one',
    binderSlot = 1,
    club = 'Arsenic',
    pos = 'ST',
    nation = 'ENG',
    attack = 84, defense = 40,
    colours = { border = '#2f5fae', plate = '#14284d' },
}

Config.Cards['card_harbour_crab'] = {
    name = 'Harbour Crab',
    theme = 'creatures',
    description = 'Lives under the Del Perro pier.',
    image = '',
    rarity = 'Epic',
    finish = 'ice',
    set = 'season_one',
    binderSlot = 2,
    element = 'tide',
    stage = 'stage1',
    hp = 90,
    move = 'Pier Pinch',
    attack = 62, defense = 71,
    colours = { border = '#2f6fb5', plate = '#10294a' },
}

Config.Cards['card_vinewood_sign'] = {
    name = 'Vinewood Sign',
    theme = 'lossantos',
    description = 'Watching over the hills since 1923.',
    image = '',
    rarity = 'Legendary',
    finish = 'gold',
    set = 'season_one',
    binderSlot = 3,
    category = 'landmark',
    district = 'vinewood',
    attack = 55, defense = 90,
    colours = { border = '#2f6fb5', plate = '#10294a' },
}

Config.CardBacks = Config.CardBacks or {}
Config.CardBacks.football = { style = 'solid', c1 = '#0e1a2e', c2 = '#1c3358', accent = '#f7d774', emblem = 'UKC', title = 'Trading Cards', sub = 'Series 1' }
Config.CardBacks.creatures = { style = 'rings', c1 = '#102a2a', c2 = '#1f5a52', accent = '#8fe3c4', emblem = '', title = 'Creature Cards', sub = 'Collect them all' }
Config.CardBacks.lossantos = { style = 'diamonds', c1 = '#1a0f2e', c2 = '#4a1d5c', accent = '#ffb347', emblem = 'LS', title = 'Los Santos', sub = 'Street cards' }

Config.Packs = Config.Packs or {}
Config.Packs['pack_street'] = { label = 'Street Pack', set = 'season_one', cards = 5, rates = { Common = 70, Uncommon = 20, Rare = 7, Epic = 2, Legendary = 1 }, guaranteed = { slot = 5, minRarity = 'Rare' } }
