-- as-tradingcards / custom/cards.lua
-- Generated by Card Creator

Config.Cards = Config.Cards or {}

Config.Cards['acestudios'] = {
    name = 'ACE Studios',
    theme = 'football',
    image = 'acestudios.png',
    rarity = 'Common',
    finish = 'ice',
    foilStrength = 1.60,
    set = 'acestudios',
    binderSlot = 1,
    club = 'ACE Studios',
    pos = 'ST',
    nation = 'ENG',
    attack = 99, defense = 99,
    colours = { border = '#0062ff', plate = '#0059ff' },
}

Config.CardBacks = Config.CardBacks or {}
Config.CardBacks.football = { style = 'solid', c1 = '#0e1a2e', c2 = '#1c3358', accent = '#ff00bb', emblem = '', title = 'ACE STUDIOS', sub = 'ACE STUDIOS', titleColour = '#00fffb', subColour = '#ff00f7' }
Config.CardBacks.creatures = { style = 'rings', c1 = '#102a2a', c2 = '#1f5a52', accent = '#8fe3c4', emblem = '', title = 'Creature Cards', sub = 'Collect them all', titleColour = '#8fe3c4', subColour = '#ffffff' }
Config.CardBacks.lossantos = { style = 'diamonds', c1 = '#1a0f2e', c2 = '#4a1d5c', accent = '#ffb347', emblem = 'LS', title = 'Los Santos', sub = 'Street cards', titleColour = '#ffb347', subColour = '#ffffff' }

Config.Packs = Config.Packs or {}
Config.Packs['pack_acestudios'] = { label = 'ACE STUDIOS Test Pack', set = 'acestudios', cards = 5, rates = { Common = 55, Uncommon = 25, Rare = 12, Epic = 5, Legendary = 2.5, Mythic = 0.5 }, guaranteed = { slot = 5, minRarity = 'Rare' } }
