-- as-tradingcards / config/playmats.lua
-- Generated by Playmat Creator. Images go in html/img/playmats/ (filename only below).

Config.PlayMats = Config.PlayMats or {}

Config.PlayMats.Order = {
    'neon_strip',
    'mossy_arena',
}

Config.PlayMats.Themes = {
        ['neon_strip'] = {
            label = 'Neon Strip',
            description = 'Vinewood Boulevard after dark.',
            style = {
                surface = 'linear-gradient(180deg, rgba(42, 15, 58, 0.94) 0%, rgba(26, 10, 42, 0.96) 44%, rgba(10, 26, 48, 0.96) 56%, rgba(6, 16, 31, 0.98) 100%)',
                border = 'rgba(255, 79, 163, 0.55)',
                shadow = '0 40px 60px rgba(0, 0, 0, 0.7), inset 0 2px 0 rgba(255, 255, 255, 0.1), inset 0 -4px 20px rgba(0, 0, 0, 0.5)',
                stitch = 'rgba(255, 211, 236, 0.35)',
                hpYou = '#38e1ff',
                hpOpp = '#ff4fa3',
                wheelYou = '#38e1ff',
                wheelOpp = '#ff4fa3',
                glowYou = 'rgba(56, 225, 255, 0.75)',
                glowOpp = 'rgba(255, 79, 163, 0.75)',
                hudBorder = 'rgba(255, 79, 163, 0.55)',
            },
            -- raw picks, used by Import Lua in the creator
            colours = {
                matTop = '#2a0f3a',
                matMidTop = '#1a0a2a',
                matMidBottom = '#0a1a30',
                matBottom = '#06101f',
                border = '#ff4fa3',
                shadowDrop = '#000000',
                shadowLight = '#ffffff',
                shadowDark = '#000000',
                stitch = '#ffd3ec',
                hpYou = '#38e1ff',
                hpOpp = '#ff4fa3',
                wheelYou = '#38e1ff',
                wheelOpp = '#ff4fa3',
                glowYou = '#38e1ff',
                glowOpp = '#ff4fa3',
                hudBorder = '#ff4fa3',
            },
        },

        ['mossy_arena'] = {
            label = 'Mossy Arena',
            description = 'Overgrown stone arena for creature battles.',
            style = {
                surface = 'linear-gradient(180deg, rgba(29, 58, 36, 0.94) 0%, rgba(20, 42, 26, 0.96) 44%, rgba(26, 47, 32, 0.96) 56%, rgba(16, 35, 26, 0.98) 100%)',
                border = 'rgba(143, 207, 122, 0.55)',
                shadow = '0 40px 60px rgba(0, 0, 0, 0.7), inset 0 2px 0 rgba(255, 255, 255, 0.1), inset 0 -4px 20px rgba(0, 0, 0, 0.5)',
                stitch = 'rgba(201, 240, 184, 0.35)',
                hpYou = '#8fe36b',
                hpOpp = '#f2a65a',
                wheelYou = '#8fe36b',
                wheelOpp = '#f2a65a',
                glowYou = 'rgba(143, 227, 107, 0.75)',
                glowOpp = 'rgba(242, 166, 90, 0.75)',
                hudBorder = 'rgba(143, 207, 122, 0.55)',
            },
            -- raw picks, used by Import Lua in the creator
            colours = {
                matTop = '#1d3a24',
                matMidTop = '#142a1a',
                matMidBottom = '#1a2f20',
                matBottom = '#10231a',
                border = '#8fcf7a',
                shadowDrop = '#000000',
                shadowLight = '#ffffff',
                shadowDark = '#000000',
                stitch = '#c9f0b8',
                hpYou = '#8fe36b',
                hpOpp = '#f2a65a',
                wheelYou = '#8fe36b',
                wheelOpp = '#f2a65a',
                glowYou = '#8fe36b',
                glowOpp = '#f2a65a',
                hudBorder = '#8fcf7a',
            },
        },
}
