-- QBCore + qb-inventory (or ps-/lj-inventory): add to qb-core/shared/items.lua
-- Item images: put ascard_*.png in your inventory's html/images/ folder

ascard_booster_pack1 = { name = 'ascard_booster_pack1', label = 'Series 1 Booster',      weight = 20,  type = 'item', image = 'ascard_booster_pack1.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'Contains 5 football cards' },
ascard_booster_pack2 = { name = 'ascard_booster_pack2', label = 'Series 1 Mega Booster', weight = 35,  type = 'item', image = 'ascard_booster_pack2.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = 'Contains 10 football cards' },
ascard_booster_box   = { name = 'ascard_booster_box',   label = 'Series 1 Booster Box',  weight = 300, type = 'item', image = 'ascard_booster_box.png',   unique = false, useable = true, shouldClose = true, combinable = nil, description = 'Contains 12 booster packs' },
ascard_player          = { name = 'ascard_player', label = 'Common Card', weight = 1, type = 'item', image = 'ascard_player.png', unique = true, useable = true, shouldClose = true, combinable = nil, description = 'A football trading card' },
ascard_star            = { name = 'ascard_star', label = 'Uncommon Card', weight = 1, type = 'item', image = 'ascard_star.png', unique = true, useable = true, shouldClose = true, combinable = nil, description = 'A football trading card' },
ascard_captain         = { name = 'ascard_captain', label = 'Rare Card', weight = 1, type = 'item', image = 'ascard_captain.png', unique = true, useable = true, shouldClose = true, combinable = nil, description = 'A football trading card' },
ascard_winner          = { name = 'ascard_winner', label = 'Epic Card', weight = 1, type = 'item', image = 'ascard_winner.png', unique = true, useable = true, shouldClose = true, combinable = nil, description = 'A football trading card' },
ascard_century         = { name = 'ascard_century', label = 'Legendary Card', weight = 1, type = 'item', image = 'ascard_century.png', unique = true, useable = true, shouldClose = true, combinable = nil, description = 'A football trading card' },
ascard_legend          = { name = 'ascard_legend', label = 'Mythic Card', weight = 1, type = 'item', image = 'ascard_legend.png', unique = true, useable = true, shouldClose = true, combinable = nil, description = 'A football trading card' },
ascard_slab          = { name = 'ascard_slab',          label = 'Graded Card',           weight = 60,  type = 'item', image = 'ascard_slab.png',          unique = true,  useable = true, shouldClose = true, combinable = nil, description = 'A professionally graded card in a sealed case' },
ascard_psa           = { name = 'ascard_psa',           label = 'Grading Case',      weight = 50,  type = 'item', image = 'ascard_psa.png',           unique = false, useable = false, shouldClose = true, combinable = nil, description = 'Hand this in with a card at the grader' },
ascard_binder        = { name = 'ascard_binder',        label = 'Card Binder',           weight = 250, type = 'item', image = 'ascard_binder.png',        unique = true,  useable = true, shouldClose = true, combinable = nil, description = 'Track your collection' },

ascard_sleeve        = { name = 'ascard_sleeve',        label = 'Penny Sleeve',          weight = 1,   type = 'item', image = 'ascard_sleeve.png',        unique = false, useable = false, shouldClose = true, combinable = nil, description = 'Protects a card from dust, fingerprints, scratches and water' },
ascard_toploader     = { name = 'ascard_toploader',     label = 'Toploader',             weight = 10,  type = 'item', image = 'ascard_toploader.png',     unique = false, useable = false, shouldClose = true, combinable = nil, description = 'Rigid case for a sleeved card' },
ascard_loupe         = { name = 'ascard_loupe',         label = 'Magnifier Loupe',       weight = 50,  type = 'item', image = 'ascard_loupe.png',         unique = true,  useable = false, shouldClose = true, combinable = nil, description = 'Inspect a card for the smallest flaws' },
ascard_cloth         = { name = 'ascard_cloth',         label = 'Microfibre Cloth',      weight = 10,  type = 'item', image = 'ascard_cloth.png',         unique = true,  useable = false, shouldClose = true, combinable = nil, description = 'Wipes dust and fingerprints off cards' },
ascard_spray         = { name = 'ascard_spray',         label = 'Card Cleaner Spray',    weight = 100, type = 'item', image = 'ascard_spray.png',         unique = true,  useable = false, shouldClose = true, combinable = nil, description = 'Lifts dirt and stains off cards' },
ascard_scale         = { name = 'ascard_scale',         label = 'Digital Pack Scale',    weight = 400, type = 'item', image = 'ascard_scale.png',         unique = true,  useable = true,  shouldClose = true, combinable = nil, description = 'Weigh sealed packs. The heavy ones might hold a hit.' },
ascard_slabcase      = { name = 'ascard_slabcase',      label = 'Slab Case',             weight = 600, type = 'item', image = 'ascard_slabcase.png',      unique = true,  useable = true,  shouldClose = true, combinable = nil, description = 'Holds 10 graded slabs (needs ox_inventory)' },
ascard_appraisal     = { name = 'ascard_appraisal',     label = 'Appraisal Letter',      weight = 10,  type = 'item', image = 'ascard_appraisal.png',     unique = true,  useable = true,  shouldClose = true, combinable = nil, description = 'An official card appraisal' },
ascard_shrinkwrap    = { name = 'ascard_shrinkwrap',    label = 'Shrink Wrap',           weight = 50,  type = 'item', image = 'ascard_shrinkwrap.png',    unique = false, useable = true,  shouldClose = true, combinable = nil, description = 'Wrap loose packs back into a box. It won’t pass a seal check.' },

ascard_fat_pack      = { name = 'ascard_fat_pack', label = 'Series 1 Fat Pack', weight = 20, type = 'item', image = 'ascard_fat_pack.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = '7 cards, at least one foil' },
ascard_blaster_pack  = { name = 'ascard_blaster_pack', label = 'Blaster Exclusive Pack', weight = 20, type = 'item', image = 'ascard_blaster_pack.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = '3 cards with a guaranteed numbered parallel' },
ascard_hobby_pack    = { name = 'ascard_hobby_pack', label = 'Series 1 Hobby Pack', weight = 20, type = 'item', image = 'ascard_hobby_pack.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = '8 cards - hobby packs are where the hits are' },
ascard_blaster       = { name = 'ascard_blaster', label = 'Series 1 Blaster Box', weight = 200, type = 'item', image = 'ascard_blaster.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = '6 boosters + 1 exclusive pack' },
ascard_hobby_box     = { name = 'ascard_hobby_box', label = 'Series 1 Hobby Box', weight = 500, type = 'item', image = 'ascard_hobby_box.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = '12 hobby packs, one guaranteed autograph or relic' },
ascard_tin           = { name = 'ascard_tin', label = 'Series 1 Collector Tin', weight = 300, type = 'item', image = 'ascard_tin.png', unique = false, useable = true, shouldClose = true, combinable = nil, description = '4 boosters + 1 limited card' },

-- Older qb-core using the ['name'] = { ['name'] = ... } format: same fields, just wrap them that way.
